spring:
  profiles:
    active: ${ENV:local}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/queries}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: ${KAFKA_URL:127.0.0.1:9092}